services:
  mongodb:
    x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
        tags: 
          - joehannis/taplist-keg-level-manager:latest
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - ./mongodb-data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v8
        tags: 
          - joehannis/taplist-keg-level-manager:latest
    container_name: api-container
    ports:
      - "3000:3000"
    networks:
      - my-network
    environment:
      MONGODB_URL: mongodb://mongodb-container:27017/taplist-klm

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v8
        tags: 
          - joehannis/taplist-keg-level-manager:latest
    container_name: frontend-container
    ports:
      - "5173:5173"
    networks:
      - my-network
    environment:
      REACT_APP_API_URL: http://api-container:3000

networks:
  my-network:
