services:
  mongodb:
    x-bake:
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
        - linux/arm/v8
      tags:
        - joehannis/taplist-keg-level-manager:latest
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    network_mode: host
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:$DB_PORT/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v8
        tags:
          - joehannis/taplist-keg-level-manager:latest
    container_name: api-container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v8
        tags:
          - joehannis/taplist-keg-level-manager:latest
    container_name: frontend-container
    ports:
      - "5173:5173"
    environment:
      REACT_APP_API_URL: http://api-container:3000
    depends_on:
      - api
    network_mode: host
