services:
  db:
    networks:
      - my-network
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taplist-keg-level-manager
    ports:
      - '5432:5432'

  api:
    networks:
      - my-network
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/taplist-integration

    ports:
      - '3000:3000'

    depends_on:
      - db

  nginx:
    networks:
      - my-network
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api

  frontend:
    networks:
      - my-network
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4173:4173'
    depends_on:
      - api

networks:
  my-network:
    driver: bridge
