services:
  api:
    networks:
      - my-network
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VENUE = ''
      - AUTH_TOKEN = ''

  frontend:
    networks:
      - my-network
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4173:4173'
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:3000

networks:
  my-network:
    driver: bridge
