name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: build the image
        run: |
          docker buildx build \
            --file ./api/Dockerfile \
            --tag joehannis/taplist-keg-level-manager:api-latest \
            --platform linux/amd64,linux/arm/v7,linux/arm/v8,linux/arm64 ./api \
            --push
          docker buildx build \
            --file ./frontend/Dockerfile \
            --tag joehannis/taplist-keg-level-manager:frontend-latest \
            --platform linux/amd64,linux/arm/v7,linux/arm/v8,linux/arm64 ./frontend \
            --push
