name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push Docker images using docker-compose
        run: |
          docker-compose -f ./docker-compose-amd64.yml build
          docker-compose -f ./docker-compose-amd64.yml push
          docker-compose -f ./docker-compose-armhf.yml build
          docker-compose -f ./docker-compose-armhf.yml push
