name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Docker images
        run: |
          docker buildx bake --set *.platform=linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm/v8 --file docker-compose.yml -t joehannis/taplist-keg-level-manager:latest . --push
