name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        id: buildx
        run: |
          docker build --platform=local -o . git://github.com/docker/buildx-bin
          chmod a+x buildx
          mkdir -p ~/.docker/cli-plugins
          mv buildx ~/.docker/cli-plugins/docker-buildx
      -
        name: Create Docker Builder Instance
        run: docker buildx create --use --name mybuilder --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
      -
        name: Build and Push Docker images using docker-compose
        run: |
          docker-compose -f ./docker-compose.yml build
          docker-compose -f ./docker-compose.yml push
