name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FRONTEND_TAG: frontend-multiarch
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create builder instance
        run: |
          docker buildx create --use --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
      -
        name: Build and Push Docker image for frontend
        run: |
          # Build and push frontend image
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 -t taplist-keg-level-manager/frontend:${FRONTEND_TAG} ./frontend --push
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 -t taplist-keg-level-manager/api:${FRONTEND_TAG} ./api --push

