name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create builder instance
        run: |
          docker buildx create --use --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm/v8
      -
        name: Build Docker images using docker-compose
        run: |
          docker-compose -f ./docker-compose.yml build
      -
        name: Push Docker images to Docker Hub
        run: |
          docker-compose -f ./docker-compose.yml push

