name: Test CI

on:
  push:
    branches:
      - 'test'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_TAG: 'test'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker images
        run: |
          docker buildx bake --push -t ${{ secrets.DOCKERHUB_USERNAME }}/taplist-keg-level-manager:${{ env.TEST_TAG }}
